name: postman-pull-request
'on':
  - push
  - pull_request
jobs:
  build: null
  runs-on: ubuntu-latest
  steps:
    - name: Install dependencies
      run: npm install
    - name: Install newman
      run: npm install -g newman
    - name: Run the API and Postman's tests
      run: >
        npm run start:dev &
        sleep 60
        newman run "OCA_APIs.json -e Environment_OCA.json -d
        CP18_PickUpCente_ByState_Validos.csv"
