name: postman-pull-request
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:       
        - name: Install newman
          run: npm install -g newman
        - name: Run the API and Postman's tests
          run: >
            newman run "CP18-API-PickUpCenter_ByState_CasosValidos.json -e Environment_OCA.json -d
            CP18_PickUpCente_ByState_Validos.csv"
