name: postman-pull-request
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build: null
  runs-on: ubuntu-latest
  steps:
    - name: Install dependencies
      run: npm install
    - name: Install newman
      run: npm install -g newman
    - name: Run the API and Postman's tests
      run: >
        npm run start:dev &
        sleep 60
        newman run "CP18-API-PickUpCenter_ByState_CasosValidos.json.json -e Environment_OCA.json -d
        CP18_PickUpCente_ByState_Validos.csv"
