name: CarpetaPostman
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  job_GetFindByState:
    runs-on: ubuntu-latest
    steps:
      - name: Install newman
        run:
          npm install -g newman          
      - name: Ejecutar Get_Pet_FindByState
        run:
          newman run "https://github.com/roacarlo/CI-CD_PetStore_repo/tree/master/PostmanCollections/Get_FindByState.json" -e "https://github.com/roacarlo/CI-CD_PetStore_repo/tree/master/PostmanCollections/petStore_Environment.json"
