name: GetFindByState
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Install newman
        run: npm install -g newman
      - name: Ejecutar API Postman CP01
        run: >-
          newman run "https://github.com/roacarlo/CI-CD_PetStore_repo/tree/master/PostmanCollections/Get_FindByState.json" -e "https://github.com/roacarlo/CI-CD_PetStore_repo/tree/master/PostmanCollections/PetStore_Environment.json"
