name: GetFindByState
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  job_GetFindByState:
    runs-on: windows-latest
    steps:
      - name: Install newman
        run: npm install -g newman
      - name: Ejecutar GetFindByState
        run: >-
              newman run "Get_FindByState.json" -e "petStore_Environment.json"
